language: c

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install libmpdclient-dev
  - wget http://security.ubuntu.com/ubuntu/pool/universe/g/glyr/libglyr-dev_1.0.5-1_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/universe/g/glyr/libglyr1_1.0.5-1_amd64.deb
  - sudo dpkg -i libglyr1_1.0.5-1_amd64.deb
  - sudo dpkg -i libglyr-dev_1.0.5-1_amd64.deb

script:
  - make && make check

